version: "3.9"

services:
  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile.react
      args:
        NODE_VERSION: "22.12"
        NGINX_VERSION: "1.22"
      target: dev
    container_name: react-app
    ports:
      - "5173:5173"
    networks:
      - react
    depends_on:
      - fastapi-app
      - flask-app
    volumes:
      # - type: bind
      #   source: ./react-app/package.json
      #   target: /app/package.json
      - type: bind
        source: ./react-app
        target: /app
      - type: volume
        target: /app/node_modules
      # - type: bind
      #   source: ./react-app/nginx.conf
      #   target: /etc/nginx/nginx.conf
      # - type: bind
      #   source: ./react-app/dist
      #   target: /usr/share/nginx/html
      # - type: bind
      #   source: ./react-app/sites
      #   target: /app/sites
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

  fastapi-app:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile.fastapi
      args:
        PYTHON_VERSION: "3.11"
      target: dev
    container_name: fastapi-app
    ports:
      - "8000:8000"
    networks:
      - fastapi
    volumes:
      - type: bind
        source: ./fastapi_app/pyproject.toml
        target: /app/pyproject.toml
      - type: bind
        source: ./fastapi_app
        target: /app
      - type: volume  
        target: /app/.venv

  flask-app:
    build:
      context: ./flask_app
      dockerfile: Dockerfile.flask
      args:
        PYTHON_VERSION: "3.11"
      target: dev
    container_name: flask-app
    ports:
      - "5000:5000"
    networks:
      - flask
    volumes:
      - type: volume
        target: /app/.venv
      - type: bind
        source: ./flask_app/pyproject.toml
        target: /app/pyproject.toml
      - type: bind
        source: ./flask_app
        target: /app

  
networks:
  react:
  fastapi:
  flask:
