version: "3.9"

services:
  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile.react
      args:
        NODE_VERSION: "22.12"
        NGINX_VERSION: "1.22"
    container_name: react-app
    ports:
      - "80:80"
      - "443:443"
    networks:
      - react
    depends_on:
      - fastapi-app
      - flask-app
    userns_mode: "remap" # With this keys, ports <= 1024 are not available because of permissions
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  fastapi-app:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile.fastapi
      args:
        PYTHON_VERSION: "3.11"
    container_name: fastapi-app
    ports:
      - "8000:8000"
    networks:
      - fastapi
    userns_mode: "remap"
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  flask-app:
    build:
      context: ./flask_app
      dockerfile: Dockerfile.flask
      args:
        PYTHON_VERSION: "3.11"
    container_name: flask-app
    ports:
      - "5000:5000"
    networks:
      - flask
    userns_mode: "remap"
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  
networks:
  react:
  fastapi:
  flask:
