ARG PYTHON_VERSION=3.11


FROM python:${PYTHON_VERSION}-slim AS base

RUN useradd -m fastapi

COPY --chown=fastapi --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

LABEL maintainer="vlad-yarko"
LABEL org.opencontainers.image.source="https://github.com/vlad-yarko/my-docker"
LABEL org.opencontainers.image.description=DESCRIPTION

WORKDIR /app

COPY --chown=fastapi pyproject.toml .


FROM base AS dev

RUN uv sync

COPY --chown=fastapi . . 

EXPOSE 8000

USER fastapi

ENTRYPOINT [ "uv", "run", "uvicorn", "main:app" ]
CMD [ "--host", "0.0.0.0", "--port", "8000", "--reload" ]


FROM base AS prod

RUN uv sync

COPY --chown=fastapi . . 

EXPOSE 8000

USER fastapi

ENTRYPOINT [ "uv", "run", "uvicorn", "main:app" ]
CMD [ "--host", "0.0.0.0", "--port", "8000" ]
