FROM python:3.11-slim AS base

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

LABEL maintainer="vladyslav-yarko"
LABEL org.opencontainers.image.source="https://github.com/vlad-yarko/my-docker"

WORKDIR /app

COPY pyproject.toml .

RUN uv sync

COPY . . 

EXPOSE 8000

CMD [ "uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" ]
