ARG PYTHON_VERSION=3.11

FROM python:${PYTHON_VERSION}-slim AS base

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

LABEL maintainer="vladyslav-yarko"
LABEL org.opencontainers.image.source="https://github.com/vlad-yarko/my-docker"

WORKDIR /app

COPY pyproject.toml .

RUN uv sync

COPY . . 

EXPOSE 8000

ENTRYPOINT [ "uv", "run", "uvicorn", "main:app" ]
CMD [ "--host", "0.0.0.0", "--port", "8000" ]
