FROM node:22.12-alpine

WORKDIR /frontend

ENV NODE_ENV production

COPY --chown=node:node package*.json .

RUN --mount=type=cache,target=/frontend/.npm \
    npm set cache /frontend/.npm && \
    npm ci --only=production

USER node

COPY --chown=node:node . .

EXPOSE 5173

CMD [ "npm", "run", "dev", "--", "--host" ]
